# Generated by Django 5.0.1 on 2024-01-22 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='avatar',
            new_name='images',
        ),
    ]
