# Generated by Django 5.0.1 on 2024-01-22 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_customuser_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='images',
        ),
    ]
