# Generated by Django 5.0.1 on 2024-01-18 04:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 18, 11, 9, 23, 817174)),
        ),
    ]
