# Generated by Django 5.0.1 on 2024-01-19 02:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_product_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 19, 9, 1, 54, 195662)),
        ),
    ]
